package it.water.permission.api;

import it.water.core.api.service.BaseEntityApi;

import it.water.permission.model.WaterPermission;

import java.util.List;
import java.util.Map;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface PermissionApi extends BaseEntityApi<WaterPermission> {
    /**
     * Returns the current logged user permission map
     *
     * @param entityPks
     * @return
     */
    Map<String, Map<String, Map<String, Boolean>>> entityPermissionMap(Map<String, List<Long>> entityPks);
}