package it.water.permission.api;

import it.water.core.api.action.ResourceAction;
import it.water.core.api.model.Resource;
import it.water.core.api.model.User;
import it.water.core.api.permission.Role;
import it.water.core.api.repository.BaseRepository;
import it.water.permission.model.WaterPermission;

import java.util.Collection;
import java.util.List;

/**
 * @Generated by Water Generator
 * Interface component for Permission Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface PermissionRepository extends BaseRepository<WaterPermission> {
    /**
     * Find a permission by a specific user and resource
     *
     * @param userId     user parameter
     * @param resource parameter required to find a resource
     * @return Permission if found
     */
    WaterPermission findByUserAndResource(long userId, Resource resource);

    /**
     * Find a permission by a specific user and resource name
     *
     * @param userId               user parameter
     * @param entityResourceName parameter required to find a resource name
     * @return Permission if found
     */
    WaterPermission findByUserAndResourceName(long userId, String entityResourceName);

    /**
     * Find a permission by a specific role, resource name and resource id
     *
     * @param userId               user parameter
     * @param entityResourceName parameter required to find a resource name
     * @param id                 parameter required to find a resource id
     * @return Permission if found
     */
    WaterPermission findByUserAndResourceNameAndResourceId(long userId,
                                                           String entityResourceName, long id);

    /**
     * Find a permission by a specific role and resource
     *
     * @param roleId     parameter required to find role by roleId
     * @param resource parameter required to find a resource
     * @return Permission if found
     */
    WaterPermission findByRoleAndResource(long roleId, Resource resource);

    /**
     * Find a permission by a specific role and resource name
     *
     * @param roleId     parameter required to find role by roleId
     * @param resourceName parameter required to find a resource
     * @return Permission if found
     */
    WaterPermission findByRoleAndResourceName(long roleId, String resourceName);


    /**
     * Find a permissions by a specific role
     *
     * @param roleId parameter required to find role by roleId
     * @return Permissions if found
     */
    Collection<WaterPermission> findByRole(long roleId);

    /**
     * Find a permission by a specific role, resource name and resource id
     *
     * @param roleId               parameter required to find role by roleId
     * @param entityResourceName parameter required to find a resource name
     * @param id                 parameter required to find a resource id
     * @return Permission if found
     */
    WaterPermission findByRoleAndResourceNameAndResourceId(long roleId,
                                                           String entityResourceName, long id);

    /**
     * @param roleId
     * @param actions List actions to add as permissions
     */
    void checkOrCreatePermissions(long roleId, List<ResourceAction> actions);

    /**
     * @param roleId
     * @param entityId
     * @param actions
     */
    void checkOrCreatePermissionsSpecificToEntity(long roleId, long entityId, List<ResourceAction> actions);

    /**
     * Verify if exist a permission specific to entity
     *
     * @param resourceName parameter required to find a resource name
     * @param resourceId   parameter required to find a resource id
     * @return true if exist a specific permission to this entity, false otherwise
     */
    boolean permissionSpecificToEntityExists(String resourceName, long resourceId);
}
