
package it.water.permission.service.rest.spring;

import it.water.core.api.model.PaginableResult;
import it.water.core.api.repository.query.Query;
import it.water.core.api.repository.query.QueryOrder;
import it.water.permission.api.rest.spring.PermissionSpringRestApi;
import it.water.permission.model.WaterPermission;
import it.water.permission.service.rest.PermissionRestControllerImpl;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for User entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class PermissionSpringRestControllerImpl extends PermissionRestControllerImpl implements PermissionSpringRestApi {
    @Override
    public WaterPermission save(WaterPermission entity) {
        return super.save(entity);
    }

    @Override
    public WaterPermission update(WaterPermission entity) {
        return super.update(entity);
    }

    @Override
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    public WaterPermission find(long id) {
        return super.find(id);
    }

    @Override
    public PaginableResult<WaterPermission> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    public PaginableResult<WaterPermission> findAll() {
        return super.findAll();
    }
}
